[package]
name = "smart-road"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rusttype = "0.9.3"

[dependencies.sdl2]
version = "0.36.0"
default-features = false
features = []

[dependencies.image]
version = "0.24"

rusttype = "0.9" 
