[package]
name = "smart-road"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.4", features = ["audio"] }
rand = "0.8.5"
once_cell = "1.18.0"
chrono = { version = "0.4.31", features = [] }
